PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION)

include $(THEOS)/makefiles/common.mk

SUBPROJECTS += ASSWatchdog libmitsuhainfinity Prefs Music Spotify SpringboardLS

include $(THEOS_MAKE_PATH)/aggregate.mk
